sudo: required

language: go

go:
  - 1.x

git:
  depth: 1

env:
  global:
    - UPXVER="3.95"

install:
  - go get -d -v ./...
  - echo "Installing upx .."
  - "{ [ -f upx/${UPXVER}/upx ]; } ||
      { curl -OL https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz;
        tar xvf upx-${UPXVER}-amd64_linux.tar.xz;
        mkdir -p upx;
        mv upx-${UPXVER}-amd64_linux upx/${UPXVER};
      }"
  - export PATH="${TRAVIS_BUILD_DIR}/upx/${UPXVER}/:${PATH}"

script:
  - go get github.com/mitchellh/gox
  - GOOS=windows go get -d -v ./...
  - gox -verbose -output docker-log-loki -os "linux" -arch "amd64" -ldflags "-s -w -X main.Version=${TRAVIS_TAG} -X main.buildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.commitId=${TRAVIS_COMMIT}"
  - upx docker-log-loki
